version: "3.4"

services:
  frontend:
    hostname: localhost
    build:
      context: .
      dockerfile: angular-app/Dockerfile
    restart: always
    links:
      - backend
    volumes:
      - .:/app
      - /app/express-server/node_modules
      - /app/angular-app/node_modules
    tty: true
    ports:
      - 8181:4200
      - 4400:49153

  backend:
    build:
      context: .
      dockerfile: express-server/Dockerfile
    restart: always
    links:
      - database
      - cache
    volumes:
      - ".:/app"
      - /app/express-server/node_modules
      - /app/angular-app/node_modules
    tty: true
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_CONNECTION=mongodb://database/mean-docker
      - CACHE_CONNECTION=redis://cache
    depends_on:
      - database
      - cache

  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379

  database:
    image: mongo
    container_name: database
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mean-docker
