version: "3.4"

services:
  frontend:
    hostname: localhost
    build:
      context: .
      dockerfile: angular-app/Dockerfile
    links:
      - backend
    volumes:
      - ".:/app"
      - /app/express-server/node_modules
      - /app/angular-app/node_modules
    tty: true
    ports:
      - 8181:4200
      - 4400:49153

  backend:
    build:
      context: .
      dockerfile: express-server/Dockerfile
    links:
      - database
    volumes:
      - ".:/app"
      - /app/express-server/node_modules
      - /app/angular-app/node_modules
    tty: true
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_CONNECTION=mongodb://database/mean-docker
    depends_on:
      - "database"

  database:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mean-docker
